version: '2'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: account
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'